# Generated by Django 5.0.3 on 2024-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceCorpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Sentence Corpus',
                'db_table': 'sentence_corpus',
            },
        ),
    ]
